# Generated by Django 2.2 on 2019-04-05 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='profile',
            index_together={('user', 'slug')},
        ),
    ]
