# Generated by Django 2.2 on 2019-04-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190405_1946'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='profile',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
