# Generated by Django 2.2 on 2019-04-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190405_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AboutMe',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='FrequentlyUtteredWords',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='MyNickNames',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='StrikingFeatures',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.PositiveIntegerField(default=91),
        ),
    ]
