# Generated by Django 2.2 on 2019-04-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190406_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='AboutMe',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='FrequentlyUtteredWords',
            new_name='frequently_uttered_words',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='MyNickNames',
            new_name='nick_names',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='StrikingFeatures',
            new_name='striking_features',
        ),
    ]
