# Generated by Django 2.2 on 2019-04-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comment',
            new_name='comment',
        ),
    ]
